### PR TITLE
Bubble width fix

### PR DESCRIPTION
**Pull request by non-descriptive**
Should be good for a lot of cases, like I've presented in #1. Not sure if I wanna fix it for something like `¯\_( ͡° ͜ʖ ͡°)_/¯`

### CODE REVIEW

**Comment by Plecra** [comment]
As a rule, the only true source of truth for text sizing is your font renderer... I've been wondering for a while if we can use terminal APIs to get the right behaviour for these alignment tasks.

**Comment by Plecra** [comment]
Yeah! Awesome :) Rust can ask terminal renderers for true text size with this:

```rs
// this leaves `msg` in the text buffer! Make sure it's overwritten if you dont want weirdness
print!("\r{msg}");
std::io::stdout().flush().unwrap();
let count = crossterm::cursor::position().unwrap().0 as usize;
print!("\r");
```

But there's a side effect of making our test suite much nastier, since we need to give the code a real TTY. unicode-width is a tidier solution in the end!

**Comment by Plecra** [comment]
Uhoh... that was probably a bit eager. Alacritty seems to get *very* confused by ligatures. Here it's rendering text at the wrong place in the input buffer. I get the sense things will be even more exciting with various linux terminals :D

```sh
marli@Elsie:/$ "¯\_( ͡° ͜ʖ ͡°)_/¯"   more
-bash: ¯\_( ͡° ͜ʖ ͡°)_/¯more: No such file or directory
```

**Comment by non-descriptive** [comment]
Yes, alacritty still [doesn't support ](https://github.com/alacritty/alacritty/issues/50) ligatures. And also I'm not sure whether axolotl should support speaking in this kind of emojis, since anyway half of the terminals will not be able to render half of the symbols in it. `git bash`, `cygwin`, default `cmd`, `powershell`, `windows terminal`, `alacritty` - on windows they render it very poorly on average for most smileys like that. Same stands for Z̯̮̦̲͓͇͔A̓̔L̠̦͓̻̩̲ͧ̾̍͝G̸̝ͥ̀̌ͫ̅̊͂O͔͓͔͚̳̫͑!̳͉̹̬͌́ fuckery aka multiple combining characters per symbol, which is basically unused in regular written text. Smiley above do some trickery, combining full-width characters (Japanees/ Chineese regular kanas aka CJK) with normal single width characters and library, I've added, doesn't make much distinction if they are that mixed.

**Review by ashleygwilliams — APPROVED** [review]
in an effort to not let perfect be the enemy of the good, i'm approving this and merging it! there's a lot of fun further things we can do here to make it even better but this is a big improvement in the meantime :)

**Pull request merged**
